[package]
name = "clickhouse"
version.workspace = true
edition.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true

[dependencies]
chainio = { path = "../chainio" }
primitives = { path = "../primitives" }

alloy.workspace = true
chrono = { workspace = true, features = ["serde"] }
clickhouse.workspace = true
derive_more.workspace = true
eyre.workspace = true
serde.workspace = true
tracing.workspace = true
url.workspace = true
hex.workspace = true

[dev-dependencies]
clickhouse.workspace = true
tokio.workspace = true

[lints]
workspace = true
