[package]
name = "api-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
server = { path = "../../crates/server" }
api = { path = "../../crates/api" }
clickhouse = { path = "../../crates/clickhouse" }
config = { path = "../../crates/config" }
dotenvy.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
eyre.workspace = true
runtime = { path = "../../crates/runtime" }

[[bin]]
name = "api-server"
path = "src/main.rs"
