[package]
name = "messages"
version.workspace = true
edition.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
chrono = { workspace = true, features = ["serde"] }

[lints]
workspace = true
