[package]
name = "inserter"
version.workspace = true
edition.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true

[dependencies]
clickhouse.workspace = true
derive_more.workspace = true
eyre.workspace = true

[lints]
workspace = true
