[package]
name = "extractor"
version.workspace = true
edition.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true

[dependencies]
alloy.workspace = true
eyre.workspace = true
tokio.workspace = true
tokio-stream.workspace = true

[lints]
workspace = true
