[package]
name = "taikoscope"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Taikoscope binary"
default-run = "taikoscope"

[[bin]]
name = "taikoscope"
path = "src/main.rs"
