[package]
name = "taikoscope"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Taikoscope binary"
default-run = "taikoscope"

[dependencies]
config = { path = "../../crates/config" }
extractor = { path = "../../crates/extractor" }
inserter = { path = "../../crates/inserter" }

clap.workspace = true
eyre.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[[bin]]
name = "taikoscope"
path = "src/main.rs"
