[package]
name = "taikoscope"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Taikoscope binary"
default-run = "taikoscope"

[dependencies]
extractor = { path = "../../crates/extractor" }
inserter = { path = "../../crates/inserter" }

eyre.workspace = true
tokio.workspace = true

[[bin]]
name = "taikoscope"
path = "src/main.rs"
