[package]
name = "processor"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Taikoscope processor binary"
default-run = "processor"

[dependencies]
config = { path = "../../crates/config" }
driver = { path = "../../crates/driver" }
extractor = { path = "../../crates/extractor" }
clickhouse = { path = "../../crates/clickhouse" }
runtime = { path = "../../crates/runtime" }
nats-utils = { path = "../../crates/nats-utils" }
messages = { path = "../../crates/messages" }

async-nats = "0.35"
alloy-primitives.workspace = true
clap.workspace = true
dotenvy.workspace = true
eyre.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[[bin]]
name = "processor"
path = "src/main.rs"
