[package]
name = "api"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clickhouse = { path = "../clickhouse" }
primitives = { path = "../primitives" }

axum.workspace = true
chrono.workspace = true
eyre.workspace = true
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
tower-http.workspace = true

[lints]
workspace = true
