[package]
name = "ingestor"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
driver = { path = "../../crates/driver" }
chainio = { path = "../../crates/chainio" }
config = { path = "../../crates/config" }
nats-utils = { path = "../../crates/nats-utils" }
dotenvy = "0.15"
clap = { version = "4.5", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1.37", features = ["full"] }
eyre = "0.6"
async-nats = "0.35"

[lints]
workspace = true